// src/services/imageService.js
//
// Photos come from public/manifest.json, which is auto-generated by
// scripts/generate-manifest.mjs from whatever files actually exist in
// public/webp/ — any filenames, any mix of jpg/jpeg/png/webp/avif. There is
// no assumption of sequential/padded numbering, so dropping in a freshly
// exported folder of photos "just works" after a manifest regeneration.
//
// public/images.json holds the small amount of *site* configuration that
// isn't derived from the photos themselves (how many to reveal per "Load
// more" click, the social-share cover image).

const MANIFEST_URL = "/manifest.json";
const SITE_CONFIG_URL = "/images.json";
const DEFAULT_BATCH_SIZE = 60;

let manifestCache = null;
let manifestPromise = null;
let siteConfigCache = null;
let siteConfigPromise = null;

function validateManifest(manifest) {
  if (!manifest || !Array.isArray(manifest.images)) {
    throw new Error(
      "Invalid manifest.json — run `npm run manifest` after adding photos to public/webp/."
    );
  }
  return manifest;
}

/**
 * Fetch + cache the photo manifest. In-flight requests are shared so
 * concurrent callers (e.g. StrictMode double-invoke) never issue duplicate
 * network requests.
 */
export async function getManifest(forceRefresh = false) {
  if (manifestCache && !forceRefresh) return manifestCache;

  if (!manifestPromise || forceRefresh) {
    manifestPromise = fetch(MANIFEST_URL, { cache: "force-cache" })
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            "Unable to load manifest.json. Run `npm run manifest` to generate it from public/webp/."
          );
        }
        return response.json();
      })
      .then((json) => {
        manifestCache = validateManifest(json);
        return manifestCache;
      })
      .catch((err) => {
        manifestPromise = null;
        throw err;
      });
  }

  return manifestPromise;
}

/**
 * Fetch + cache lightweight site settings. Missing/malformed values fall
 * back to sane defaults rather than failing the whole gallery — this file
 * is optional.
 */
export async function getSiteConfig(forceRefresh = false) {
  if (siteConfigCache && !forceRefresh) return siteConfigCache;

  if (!siteConfigPromise || forceRefresh) {
    siteConfigPromise = fetch(SITE_CONFIG_URL, { cache: "force-cache" })
      .then((response) => (response.ok ? response.json() : {}))
      .catch(() => ({}))
      .then((json) => {
        siteConfigCache = {
          batchSize: Number(json?.batchSize) > 0 ? Number(json.batchSize) : DEFAULT_BATCH_SIZE,
          coverImage: json?.coverImage || "/cover.webp",
        };
        return siteConfigCache;
      });
  }

  return siteConfigPromise;
}

/**
 * Turn manifest entries into the shape the rest of the app uses. Kept as a
 * separate step (rather than using manifest.images directly) so we always
 * have a stable fallback `alt` and can evolve the shape later without
 * touching the manifest format.
 */
export function buildImageList(manifest) {
  return manifest.images.map((image) => ({
    id: image.id,
    filename: image.filename,
    src: image.src,
    alt: image.alt || `Wedding photo ${image.id}`,
    width: image.width,
    height: image.height,
  }));
}

/** Warm the browser's image cache for the first N images. */
export function prefetchImages(images = [], limit = 12) {
  if (!Array.isArray(images) || typeof window === "undefined") return;

  const count = Math.min(images.length, limit);
  for (let i = 0; i < count; i++) {
    const img = new window.Image();
    img.decoding = "async";
    img.src = images[i].src;
  }
}

export function clearGalleryCache() {
  manifestCache = null;
  manifestPromise = null;
  siteConfigCache = null;
  siteConfigPromise = null;
}
